using System.Text.Json.Serialization;
using TFA.Domain.Data;

namespace TFA.Domain.Models.Players;

public sealed record Player(
    [property: JsonPropertyName("player_id")] int Id,
    [property: JsonPropertyName("first_name")] string? FirstName,
    [property: JsonPropertyName("last_name")] string? LastName,
    [property: JsonPropertyName("display_name")] string? DisplayName,
    [property: JsonPropertyName("full_name")] string? FullName,
    [property: JsonPropertyName("price")] decimal Price,
    [property: JsonPropertyName("team_id")] int TeamId,
    [property: JsonPropertyName("form")] string Form,
    [property: JsonPropertyName("form_rank")] int FormRank,
    [property: JsonPropertyName("season_value")] string? SeasonValue,
    [property: JsonPropertyName("position")] PlayerPosition Position,
    [property: JsonPropertyName("chance_of_playing_this_round")] int ChanceOfPlayingThisRound,
    [property: JsonPropertyName("chance_of_playing_next_round")] int ChanceOfPlayingNextRound,
    [property: JsonPropertyName("selected_by_percent")] string? SelectedByPercent,
    [property: JsonPropertyName("yellow_cards")] int YellowCards,
    [property: JsonPropertyName("red_cards")] int RedCards,
    [property: JsonPropertyName("goals_scored")] int Goals,
    [property: JsonPropertyName("assists")] int Assists,
    [property: JsonPropertyName("clean_sheets")] int CleanSheets,
    [property: JsonPropertyName("clean_sheets_per_90")] decimal CleanSheetsPerMatch,
    [property: JsonPropertyName("goals_conceded")] int GoalsConceded,
    [property: JsonPropertyName("minutes_played")] int MinutesPlayed,
    [property: JsonPropertyName("saves")] int Saves,
    [property: JsonPropertyName("saves_per_90")] decimal? SavesPerMatch,
    [property: JsonPropertyName("bonus")] int BonusPoints,
    [property: JsonPropertyName("bps")] int Bps,
    [property: JsonPropertyName("total_points")] int TotalPoints,
    [property: JsonPropertyName("points_per_game")] string? PointsPerGame,
    [property: JsonPropertyName("expected_points_current_gameweek")] string? ExpectedPointsCurrentGameweek,
    [property: JsonPropertyName("expected_points_next_gameweek")] string? ExpectedPointsNextGameweek,
    [property: JsonPropertyName("corners_order")] int? CornersOrder,
    [property: JsonPropertyName("freekicks_order")] int? FreekicksOrder,
    [property: JsonPropertyName("penalties_order")] int? PenaltiesOrder,
    [property: JsonPropertyName("player_status")] string? Status,
    [property: JsonPropertyName("player_news")] string? News,
    [property: JsonPropertyName("player_news_added")] DateTime? NewsAdded,
    [property: JsonPropertyName("expected_goals")] string? ExpectedGoals,
    [property: JsonPropertyName("expected_goals_per_90")] decimal? ExpectedGoalsPerMatch,
    [property: JsonPropertyName("expected_assists")] string? ExpectedAssists,
    [property: JsonPropertyName("expected_assists_per_90")] decimal? ExpectedAssistsPerMatch,
    [property: JsonPropertyName("expected_goal_involvements")] string? ExpectedGoalsInvolvement,
    [property: JsonPropertyName("expected_goal_involvements_per_90")] decimal? ExpectedGoalsInvolvementPerMatch,
    [property: JsonPropertyName("expected_goals_conceded")] string? ExpectedGoalsConceded,
    [property: JsonPropertyName("expected_goals_conceded_per_90")] decimal? ExpectedGoalsConcededPerMatch,
    [property: JsonPropertyName("transfers_in_total")] int TransfersInTotal,
    [property: JsonPropertyName("transfers_in_current_gameweek")] int TransfersInGameweek,
    [property: JsonPropertyName("transfers_out_total")] int TransfersOutTotal,
    [property: JsonPropertyName("transfers_out_current_gameweek")] int TransfersOutGameweek,
    [property: JsonPropertyName("attacking_bonus")] int AttackingBonus,
    [property: JsonPropertyName("defending_bonus")] int DefendingBonus,
    [property: JsonPropertyName("key_passes")] int KeyPasses,
    [property: JsonPropertyName("clearances_blocks_interceptions")] int ClearancesBlocksInterceptions,
    [property: JsonPropertyName("price_falls_total")] int PriceFallsTotal,
    [property: JsonPropertyName("price_falls_gameweek")] int PriceFallsGameweek,
    [property: JsonPropertyName("price_rises_total")] int PriceRisesTotal,
    [property: JsonPropertyName("price_rises_gameweek")] int PriceRisesGameweek) : IEntity;

